# Generated by Django 3.2.9 on 2021-12-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='things',
            old_name='title',
            new_name='trrrritle',
        ),
    ]
