# Generated by Django 3.2.9 on 2021-12-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_title_things_trrrritle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='things',
            old_name='trrrritle',
            new_name='title',
        ),
    ]
